name: doggzi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  firebase_core: ^3.14.0
  firebase_analytics: ^11.5.0
  firebase_crashlytics: ^4.3.7
  firebase_performance: ^0.10.1+7
  flutter_svg: ^2.2.0
  shimmer: ^3.0.0
  pinput: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
