name: doggzi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.22+23

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  get_storage: ^2.1.1
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  firebase_core: ^2.32.0
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  firebase_performance: ^0.9.4+7
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  pinput: ^4.0.0
  fluttertoast: ^8.2.12
  zoom_tap_animation: ^1.1.0
  carousel_slider: ^5.1.1
  font_awesome_flutter: ^10.8.0
  onesignal_flutter: ^5.3.4
  cached_network_image: ^3.4.1
  loading_animation_widget: ^1.3.0
  flutter_staggered_grid_view: ^0.7.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png" # Your app icon
  remove_alpha_ios: true
  background_color: "#F2E7CB" # background color for the icon
  adaptive_icon_background: "#F2E7CB" # background color for the adaptive icon
flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: assets/images/splash_icon.png # splash image (centered)
  android_12:
    image: assets/images/splash_icon.png # splash image for Android 12 (centered)


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope-regular.ttf
        - asset: assets/fonts/manrope-medium.ttf
          weight: 500
        - asset: assets/fonts/manrope-semiBold.ttf
          weight: 600